### ISSUE TITLE
WiFi-Name - Special characters will be translated

### ISSUE THREAD

**Issue by JoeBananski** [eamars/OpenTrickler-RP2040-Controller#17]
If you assign a WiFi name with a comma It is stored incorrectly in the RPi. 

Example: 
fritzbox7590-2,4 becomes fritz7590-2%2C4.

EDIT:
I believe that the problem is also present with WiFi passwords. My WiFi password contains symbols like $!& etc. (but no comma!) and the connection cannot be established. My Fritzbox blocks it. If I make a guest account with numbers, the connection is established.

**Comment by eamars** [comment]
Note to myself
`http_find_file` could be modified to decode URI. 
Ref: 
https://stackoverflow.com/questions/2673207/c-c-url-decode-library
https://www.mail-archive.com/lwip-users@nongnu.org/msg17585.html
