### ISSUE TITLE
Scale Settings

### ISSUE THREAD

**Issue by Mojojojo31** [eamars/OpenTrickler-RP2040-Controller#6]
Hey,
which settings do I need to change on the scale?
Currently it stops at "Waiting for Zero".
Allready changed the baudrate to 19200bps.
So in the "settings" the scale calibration will work.
Greatings

**Comment by eamars** [comment]
As far I can recall, things need to be configured are:
1. Unit (default is Gram. Need to be maually changed to grain). 
2. Serial baud rate (to the maiximum 19200bps). 
3. Response time (to fast). 
You could use AutoTrickler manual as the reference: https://cdn.shopify.com/s/files/1/0525/7235/6768/files/AutoTrickler_V4_Sept_2022.pdf?v=1671110335

**Comment by Mojojojo31** [comment]
I still got the "--- Waiting for zero" message and it wont go any further.

**Comment by eamars** [comment]
By default the A&D Fx series scale won't automatically populate the measurement to the serial port you need to enable that. 

If you enter the Cleanup mode you should be able to read the current weight from the scale. Are you getting anything?

**Comment by Mojojojo31** [comment]
I enabled it. Got the factory settings and the AutoTrickler settings.
I also played with all settings but no change.
When I enter the Cleanup theres a black screen and when the turn the nobe the stepper will start to run. But no display output.
Maybe my scale is bad ?
But communication works because the scale will correctly respond to the calibration mode.

**Comment by eamars** [comment]
There are two issues according to your description. 

1. The OpenTrickler cannot receive/decode the message. I suggest you to check with the RX terminal on the board to see if the voltage will drop below 12V/3.3V (depending on where you measure it). 
2. The cleanup mode should not end up in blank screen. Are you running the latest firmware from https://github.com/eamars/OpenTrickler-RP2040-Controller/actions/runs/5411318698 ?

**Comment by Mojojojo31** [comment]
1. I´ve got 3,3V on RX and TX .
   RXD is 0V not changing.
   TXD got -5V

2. Yes its the latest firmware.

**Comment by eamars** [comment]
The voltage certainly raises concern here. 

First of all what chip are you using for RS232 to serial converter? For MAX3232 you're suppose to measure 3.3v (idle) or 0v (transmit/receive) at the MCU side (RX, TX test pad). 

If you're measuring the RS232 side (RXD, TXD test pad) you're suppose to measure 0V or 12V accordingly. 

The serial is active low, which means you're suppose to measure 3.3V if no communication is happening and 0V if the data bit is high. If the connection with the scale is normal and the scale is passively sending bits over then you should read something around 1.6V (and unstable) at the RX test pad.

**Comment by eamars** [comment]
Hi
I created a discord server for open trickler users. https://discord.gg/ZhdThA2vrW

Please feel free to join the server and let's work on the comm issue.

**Comment by Mojojojo31** [comment]
After some Digging on the Discord i got the Problem and the Fix. It was the v1.0rc Board and a FEMALE header 
![image](https://github.com/eamars/OpenTrickler-RP2040-Controller/assets/131718936/8271eb81-8fe7-4356-a324-42bed02b2e9f)

**Comment by eamars** [comment]
Glad the issue is fixed. Will close.
